### ISSUE TITLE
Spikes take away a player life

### ISSUE THREAD

**Issue by breadraptor** [c1phr/cs413_tiles#11]
and return them to the beginning of the screen

**Comment by rdbatch** [comment]
I'm going to start with getting the spikes to reset the character and then we can add lives pretty easily after that.

**Comment by rdbatch** [comment]
Spikes now work and reset the character back to the beginning of the level: 8f76721c451fe6d87f5eda7dad579aa2bcb3543b

**Comment by breadraptor** [comment]
spikes now take away a life ce77e3d0551cf628b75b0e05ab77f9742c12464c
